name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }} (${{ matrix.os }})
    timeout-minutes: 5
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        nodejs: [22, 24]
        os: [ubuntu-latest, macOS-latest]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint --no-fix

      - name: Format
        run: pnpm format --no-write --check

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm coverage
